<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ValuationAsset.Domain\ValuationAsset.Domain.csproj" />
		<ProjectReference Include="..\ValuationAsset.Application\ValuationAsset.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.64" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>

</Project>